services:
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    networks:
      - br1
      - networking_default
    environment:
      DEBUG: false
      PGID: 100
      PUID: 99
      TZ: Australia/Brisbane
      UMASK: 22
    tmpfs:
      - /config/logs:mode=1777
    volumes:
      - /mnt/cache/appdata/sabnzbd/config:/config
      - /mnt/user/downloads:/downloads
      - /mnt/user/downloads/incomplete/sabnzbd:/incomplete
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sabnzbd-logo.png
      - net.unraid.docker.webui=https://sabnzbd.mist-chicken.dedyn.io
      - traefik.enable=true
      - traefik.docker.network=networking_default
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.mist-chicken.dedyn.io`)
      - traefik.http.routers.sabnzbd.entrypoints=https
      - traefik.http.routers.sabnzbd.tls=true
      - traefik.http.routers.sabnzbd.tls.certresolver=desec
      - traefik.http.routers.sabnzbd.service=sabnzbd
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
      - traefik.http.services.sabnzbd.loadbalancer.server.scheme=http
    healthcheck:
      test: nc -zv 127.0.0.1 8080
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    networks:
      - br1
      - networking_default
    environment:
      DEBUG: false
      PGID: 100
      PUID: 99
      TZ: Australia/Brisbane
      UMASK: 022
      WEBUI_PORT: 8000
    tmpfs:
      - /config/logs:mode=1777
    volumes:
      - /mnt/cache/appdata/qbittorrent/config:/config
      - /mnt/user/downloads:/downloads
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qbittorrent-logo.png
      - net.unraid.docker.webui=https://qbittorrent.mist-chicken.dedyn.io
      - traefik.enable=true
      - traefik.docker.network=networking_default
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.mist-chicken.dedyn.io`)
      - traefik.http.routers.qbittorrent.entrypoints=https
      - traefik.http.routers.qbittorrent.tls=true
      - traefik.http.routers.qbittorrent.service=qbittorrent
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8000
      - traefik.http.services.qbittorrent.loadbalancer.server.scheme=http
    healthcheck:
      test: nc -zv 127.0.0.1 8000
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr
    container_name: prowlarr
    networks:
      - br1
      - networking_default
    environment:
      DEBUG: false
      PGID: 100
      PUID: 99
      TZ: Australia/Brisbane
      UMASK: 022
    tmpfs:
      - /config/logs:mode=1777
    volumes:
      - /mnt/cache/appdata/prowlarr/config:/config
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-logo.png
      - net.unraid.docker.webui=https://prowlarr.mist-chicken.dedyn.io
      - traefik.enable=true
      - traefik.docker.network=networking_default
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.mist-chicken.dedyn.io`)
      - traefik.http.routers.prowlarr.entrypoints=https
      - traefik.http.routers.prowlarr.tls=true
      - traefik.http.routers.prowlarr.service=prowlarr
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr.tls.certresolver=desec
      - traefik.http.services.prowlarr.loadbalancer.server.scheme=http
    healthcheck:
      test: nc -zv 127.0.0.1 9696
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    networks:
      - br1
      - networking_default
    environment:
      DEBUG: false
      PGID: 100
      PUID: 99
      TZ: Australia/Brisbane
      UMASK: 022
    tmpfs:
      - /config/logs:mode=1777
    volumes:
      - /mnt/cache/appdata/sonarr/config:/config
      - /mnt/user/tv:/mnt/user/tv
      - /mnt/user/downloads:/downloads
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sonarr-logo.png
      - net.unraid.docker.webui=https://sonarr.mist-chicken.dedyn.io
      - traefik.enable=true
      - traefik.docker.network=networking_default
      - traefik.http.routers.sonarr.rule=Host(`sonarr.mist-chicken.dedyn.io`)
      - traefik.http.routers.sonarr.entrypoints=https
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.tls.certresolver=desec
      - traefik.http.routers.sonarr.service=sonarr
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.services.sonarr.loadbalancer.server.scheme=http
    healthcheck:
      test: nc -zv 127.0.0.1 8989
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    networks:
      - br1
      - networking_default
    environment:
      DEBUG: false
      PGID: 100
      PUID: 99
      TZ: Australia/Brisbane
      UMASK: 022
    tmpfs:
      - /config/logs:mode=1777
    volumes:
      - /mnt/cache/appdata/radarr/config:/config
      - /mnt/user/movies:/mnt/user/movies
      - /mnt/user/downloads:/downloads
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/radarr-logo.png
      - net.unraid.docker.webui=https://radarr.mist-chicken.dedyn.io
      - traefik.enable=true
      - traefik.docker.network=networking_default
      - traefik.http.routers.radarr.rule=Host(`radarr.mist-chicken.dedyn.io`)
      - traefik.http.routers.radarr.entrypoints=https
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=desec
      - traefik.http.routers.radarr.service=radarr
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.services.radarr.loadbalancer.server.scheme=http
    healthcheck:
      test: nc -zv 127.0.0.1 7878
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    networks:
      - br1
      - networking_default
    environment:
      DEBUG: false
      PGID: 100
      PUID: 99
      TZ: Australia/Brisbane
      UMASK: 022
    tmpfs:
      - /config/logs:mode=1777
    volumes:
      - /mnt/cache/appdata/lidarr/config:/config
      - /mnt/user/music:/mnt/user/music
      - /mnt/user/downloads:/downloads
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lidarr-logo.png
      - net.unraid.docker.webui=https://lidarr.mist-chicken.dedyn.io
      - traefik.enable=true
      - traefik.docker.network=networking_default
      - traefik.http.routers.lidarr.rule=Host(`lidarr.mist-chicken.dedyn.io`)
      - traefik.http.routers.lidarr.entrypoints=https
      - traefik.http.routers.lidarr.tls=true
      - traefik.http.routers.lidarr.tls.certresolver=desec
      - traefik.http.routers.lidarr.service=lidarr
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
      - traefik.http.services.lidarr.loadbalancer.server.scheme=http
    healthcheck:
      test: nc -zv 127.0.0.1 8686
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  tdarr:
    image: ghcr.io/haveagitgat/tdarr
    container_name: tdarr
    networks:
      - networking_default
    environment:
      PUID: 99
      PGID: 100
      TZ: Australia/Brisbane
      internalNode: 'true'
    tmpfs:
      - /app/logs:mode=1777
    volumes:
      - /mnt/cache/appdata/tdarr/server:/app/server
      - /mnt/cache/appdata/tdarr/configs:/app/configs
      - /mnt/cache/appdata/tdarr/temp:/temp
      - /mnt/user/movies:/movies
      - /mnt/user/tv:/tv
    devices:
      - /dev/dri:/dev/dri
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/HaveAGitGat/Tdarr/master/Docs/Images/tdarr_logo.png
      - net.unraid.docker.webui=https://tdarr.mist-chicken.dedyn.io
      - traefik.enable=true
      - traefik.docker.network=networking_default
      - traefik.http.routers.tdarr.rule=Host(`tdarr.mist-chicken.dedyn.io`)
      - traefik.http.routers.tdarr.entrypoints=https
      - traefik.http.routers.tdarr.tls=true
      - traefik.http.routers.tdarr.tls.certresolver=desec
      - traefik.http.routers.tdarr.service=tdarr
      - traefik.http.services.tdarr.loadbalancer.server.port=8265
      - traefik.http.services.tdarr.loadbalancer.server.scheme=http
    healthcheck:
      test: nc -zv 127.0.0.1 8265
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    networks:
      - br1
      - networking_default
    environment:
      TZ: Australia/Brisbane
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/FlareSolverr/FlareSolverr/master/resources/flaresolverr_logo.png
      - net.unraid.docker.webui=https://flaresolverr.zero
    healthcheck:
      test: curl -f http://127.0.0.1:8191/
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

networks:
  br1:
    external: true
  networking_default:
    external: true
