services:
  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    networks:
      br0:
        ipv4_address: 192.168.1.254
      default:
      br1:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/cache/appdata/traefik/traefik.toml:/etc/traefik.toml:ro
      # - /mnt/cache/appdata/certs:/certs
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/ibracorp/unraid-templates/master/icons/traefik.png
      - net.unraid.docker.webui=http://192.168.1.254:8080
    healthcheck:
      test: nc -zv 127.0.0.1 443
      interval: 30s
      timeout: 5s
      retries: 3
    command:
      - '--log.level=INFO'
      - '--accesslog=true'
      - '--accesslog.filters.statuscodes=400-499,500-599'
      - '--api.dashboard=true'
      - '--api.insecure=true'
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.filename=/etc/traefik.toml'
      - '--entryPoints.https.address=:443'
      # - '--certificatesresolvers.desec.acme.dnschallenge.disablePropagationCheck=true'
      # - '--certificatesresolvers.desec.acme.dnschallenge=true'
      # - '--certificatesresolvers.desec.acme.dnschallenge.provider=desec'
      # - '--certificatesresolvers.desec.acme.email=crouchingmuppet@icloud.com'
      # - '--certificatesresolvers.desec.acme.storage=/certs/desec.json'

  iventoy:
    container_name: iventoy
    image: ziggyds/iventoy
    restart: unless-stopped
    volumes:
      - /mnt/user/isos:/app/iso
    environment:
      AUTO_START_PXE: 1
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/Core-i99/unraid-docker-templates/main/templates/icons/iventoy.png
      - net.unraid.docker.webui=http://zero.localdomain:26000
    healthcheck:
      test: pidof iventoy || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    network_mode: host
    privileged: true

# dedyn:
#   build: /mnt/cache/appdata/dynamicdns
#   container_name: dedyn
#   labels:
#     - net.unraid.docker.icon=https://desec-status.net/logo.png
#     - com.centurylinklabs.watchtower.enable=false
#   healthcheck:
#     test: pidof script.sh || exit 1
#     interval: 30s
#     timeout: 5s
#     retries: 3
#     start_period: 5s
#   restart: unless-stopped    

networks:
  default:
  br0:
    external: true
  br1:
    external: true
