services:
  dozzle:
    image: ghcr.io/prophetse7en/dozzle
    container_name: dozzle
    networks:
      - networking_default
    environment:
      TZ: Australia/Brisbane
      DOZZLE_BASE: /
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_AUTH_PROVIDER: none
      DOZZLE_NO_ANALYTICS: true      
    volumes:
      - /mnt/user/appdata/dozzle:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/dozzle.png
      - net.unraid.docker.webui=https://dozzle.mist-chicken.dedyn.io
      - traefik.enable=true
      - traefik.docker.network=networking_default
      - traefik.http.routers.dozzle.rule=Host(`dozzle.mist-chicken.dedyn.io`)
      - traefik.http.routers.dozzle.entrypoints=https
      - traefik.http.routers.dozzle.tls=true
      - traefik.http.routers.dozzle.tls.certresolver=desec
      - traefik.http.routers.dozzle.service=dozzle
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
      - traefik.http.services.dozzle.loadbalancer.server.scheme=http
    restart: unless-stopped

  nas-doctor:
    image: ghcr.io/mcdays94/nas-doctor
    container_name: nas-doctor
    networks:
      - networking_default
    environment:
      TZ: Australia/Sydney
      NAS_DOCTOR_INTERVAL: 24h
    volumes:
      - /mnt/user/appdata/nas-doctor:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/local/emhttp:/var/local/emhttp:ro
      - /dev:/dev:ro
      - /sys:/sys:ro
      - /boot:/host/boot:ro
      - /var/log:/host/log:ro
      - /etc/unraid-version:/etc/unraid-version:ro
      - /mnt:/host/mnt:ro
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/mcdays94/nas-doctor/main/icons/icon3.png
      - net.unraid.docker.webui=https://nasdoctor.mist-chicken.dedyn.io
      - traefik.enable=true
      - traefik.docker.network=networking_default
      - traefik.http.routers.nasdoctor.rule=host(`nasdoctor.mist-chicken.dedyn.io`)
      - traefik.http.routers.nasdoctor.entrypoints=https
      - traefik.http.routers.nasdoctor.tls=true
      - traefik.http.routers.nasdoctor.tls.certresolver=desec
      - traefik.http.routers.nasdoctor.service=nasdoctor
      - traefik.http.services.nasdoctor.loadbalancer.server.port=8060
      - traefik.http.services.nasdoctor.loadbalancer.server.scheme=http
    privileged: true
    restart: unless-stopped

networks:
  networking_default:
    external: true